name: Dockerized Job on riscv64

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    container:
      image: riscv64/debian:trixie
    steps:
      - name: Install libatomic
        run: apt-get update && apt-get install -y libatomic1
      
      - uses: actions/checkout@v3
      
      - name: Show Kernel Version
        run: uname -a
