name: Dockerized Job on riscv64

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    container:
      image: riscv64/ubuntu:22.04
    steps:
      - uses: actions/checkout@v3

      - name: Install node (for riscv64)
        run: |
          apt-get update
          apt-get install -y curl ca-certificates
          curl -fsSL https://deb.nodesource.com/setup_18.x | bash -
          apt-get install -y nodejs

      - name: Show node version
        run: node -v
