name: Dockerized Job on riscv64

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    container:
      image: riscv64/debian:trixie-slim
    steps:
      - uses: actions/checkout@v3

      - name: Show OS
        run: cat /etc/os-release

      - name: Show Kernel Version
        run: uname -a
