name: Dockerized Job

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    container:
      image: node:20
    steps:
      - uses: actions/checkout@v3

      - name: Show node version
        run: node -v

      - name: List current directory files
        run: ls -la
