jobs:
  build:
    runs-on: self-hosted
    container:
      image: ubuntu:22.04
    steps:
      - name: Install missing libs
        run: |
          apt update && apt install -y libatomic1 ca-certificates curl
      - uses: actions/checkout@v3
      - name: Test command
        run: node -v
