name: Dockerized Job

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted
    container:
      image: ubuntu:22.04
    steps:
      - uses: actions/checkout@v3
      - name: Show container info
        run: |
          echo "Running inside Docker"
          cat /etc/os-release
          uname -a
